In [37]:
!pip3 install scikit-learn

Requirement already satisfied: scikit-learn in /Users/eshantharjun/.pyenv/versions/3.10.16/lib/python3.10/site-packages (1.7.2)
Requirement already satisfied: numpy>=1.22.0 in /Users/eshantharjun/.pyenv/versions/3.10.16/lib/python3.10/site-packages (from scikit-learn) (2.2.6)
Requirement already satisfied: scipy>=1.8.0 in /Users/eshantharjun/.pyenv/versions/3.10.16/lib/python3.10/site-packages (from scikit-learn) (1.15.3)
Requirement already satisfied: joblib>=1.2.0 in /Users/eshantharjun/.pyenv/versions/3.10.16/lib/python3.10/site-packages (from scikit-learn) (1.6.0)
Requirement already satisfied: threadpoolctl>=3.1.0 in /Users/eshantharjun/.pyenv/versions/3.10.16/lib/python3.10/site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: cloudpickle>=3.0 in /Users/eshantharjun/.pyenv/versions/3.10.16/lib/python3.10/site-packages (from joblib>=1.2.0->scikit-learn) (3.1.2)

[notice] A new release of pip is available: 26.2 -> 26.2.1
[notice] To update, run: pip install --upgrade pip

In [38]:
import sklearn
import pandas as pd

In [39]:
print(sklearn.__version__)

1.7.2

In [40]:
df=pd.read_csv('/Users/eshantharjun/Desktop/ml/data/titanicdataset.csv')
df['Survived'].value_counts()

Survived
0    549
1    342
Name: count, dtype: int64

In [41]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [42]:
df.count()

PassengerId    891
Survived       891
Pclass         891
Name           891
Sex            891
Age            714
SibSp          891
Parch          891
Ticket         891
Fare           891
Cabin          204
Embarked       889
dtype: int64

In [43]:
# age medaina
# embarked  2 drop
# cabin name ticket passid
df = df.drop(['Cabin', 'Ticket', 'Name', 'PassengerId'], axis=1)
df['Age'] = df['Age'].fillna(df['Age'].median())
df.dropna(subset='Embarked',inplace=True)
df.head()

   Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C
2         1       3  female  26.0      0      0   7.9250        S
3         1       1  female  35.0      1      0  53.1000        S
4         0       3    male  35.0      0      0   8.0500        S

In [44]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 889 entries, 0 to 890
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Survived  889 non-null    int64
 1   Pclass    889 non-null    int64
 2   Sex       889 non-null    object
 3   Age       889 non-null    float64
 4   SibSp     889 non-null    int64
 5   Parch     889 non-null    int64
 6   Fare      889 non-null    float64
 7   Embarked  889 non-null    object
dtypes: float64(2), int64(4), object(2)
memory usage: 62.5+ KB

In [45]:
x=df.drop('Survived',axis=1)
y=df['Survived']

In [46]:
print(x.head())
y.head()

   Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0       3    male  22.0      1      0   7.2500        S
1       1  female  38.0      1      0  71.2833        C
2       3  female  26.0      0      0   7.9250        S
3       1  female  35.0      1      0  53.1000        S
4       3    male  35.0      0      0   8.0500        S

0    0
1    1
2    1
3    1
4    0
Name: Survived, dtype: int64

In [47]:
from sklearn.model_selection import train_test_split

In [48]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [49]:
x_test.count()

Pclass      178
Sex         178
Age         178
SibSp       178
Parch       178
Fare        178
Embarked    178
dtype: int64

In [50]:
x_train.head()

     Pclass     Sex   Age  SibSp  Parch      Fare Embarked
708       1  female  22.0      0      0  151.5500        S
240       3  female  28.0      1      0   14.4542        C
382       3    male  32.0      0      0    7.9250        S
792       3  female  28.0      8      2   69.5500        S
683       3    male  14.0      5      2   46.9000        S

In [51]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

In [52]:
from sklearn.neighbors import KNeighborsClassifier
model=KNeighborsClassifier()
model.fit(x_train,y_train)

ValueError: could not convert string to float: 'female'

In [54]:
cat_cols=['Sex',"Embarked"]

In [55]:
ct=ColumnTransformer([('cat',OneHotEncoder(sparse_output=False),cat_cols)],remainder='passthrough')
x_train_final = ct.fit_transform(x_train)
x_test_final=ct.fit_transform(x_test)

In [56]:
x_train.shape
x_train_final.shape

(711, 10)