In [74]:
import pandas as pd
import numpy as np

In [3]:
df=pd.read_csv('../data/tipss.csv')
df.info()
df

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    object
 3   smoker      244 non-null    object
 4   day         244 non-null    object
 5   time        244 non-null    object
 6   size        244 non-null    int64
dtypes: float64(2), int64(1), object(4)
memory usage: 13.5+ KB

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [4]:
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [6]:
type(df['day'])

pandas.core.series.Series

In [11]:
df[['total_bill','day','tip']].head()

   total_bill  day   tip
0       16.99  Sun  1.01
1       10.34  Sun  1.66
2       21.01  Sun  3.50
3       23.68  Sun  3.31
4       24.59  Sun  3.61

In [12]:
df['country']='india'
df.head()

   total_bill   tip     sex smoker  day    time  size country
0       16.99  1.01  Female     No  Sun  Dinner     2   india
1       10.34  1.66    Male     No  Sun  Dinner     3   india
2       21.01  3.50    Male     No  Sun  Dinner     3   india
3       23.68  3.31    Male     No  Sun  Dinner     2   india
4       24.59  3.61  Female     No  Sun  Dinner     4   india

In [15]:
df['biil_per_person']=round(df['total_bill']/df['size'],2)
df.head()

   total_bill   tip     sex smoker  day    time  size country  biil_per_person
0       16.99  1.01  Female     No  Sun  Dinner     2   india             8.49
1       10.34  1.66    Male     No  Sun  Dinner     3   india             3.45
2       21.01  3.50    Male     No  Sun  Dinner     3   india             7.00
3       23.68  3.31    Male     No  Sun  Dinner     2   india            11.84
4       24.59  3.61  Female     No  Sun  Dinner     4   india             6.15

In [18]:
df['total_paid']=df['tip']+df['total_bill']
df.head()
df.shape

(244, 10)

In [35]:
df.iloc[6:10:2]
df.iloc[[0,1,2,3]]
df.iloc[10:21,2:6:2]
df.iloc[6]
df.iloc[-1]
df.iloc[1:6]

,total_bill,tip,sex,smoker,day,time,size,country,biil_per_person,total_paid
1,10.34,1.66,Male,No,Sun,Dinner,3,india,3.45,12.00
2,21.01,3.50,Male,No,Sun,Dinner,3,india,7.00,24.51
3,23.68,3.31,Male,No,Sun,Dinner,2,india,11.84,26.99
4,24.59,3.61,Female,No,Sun,Dinner,4,india,6.15,28.20
5,25.29,4.71,Male,No,Sun,Dinner,4,india,6.32,30.00

In [37]:
print(list(df.columns))
df.iloc[10:15,[4,0]]

['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size', 'country', 'biil_per_person', 'total_paid']

    day  total_bill
10  Sun       10.27
11  Sun       35.26
12  Sun       15.42
13  Sun       18.43
14  Sun       14.83

In [40]:
df.iloc[(df['size']>4).values]

,total_bill,tip,sex,smoker,day,time,size,country,biil_per_person,total_paid
125,29.80,4.20,Female,No,Thur,Lunch,6,india,4.97,34.00
141,34.30,6.70,Male,No,Thur,Lunch,6,india,5.72,41.00
142,41.19,5.00,Male,No,Thur,Lunch,5,india,8.24,46.19
143,27.05,5.00,Female,No,Thur,Lunch,6,india,4.51,32.05
155,29.85,5.14,Female,No,Sun,Dinner,5,india,5.97,34.99
156,48.17,5.00,Male,No,Sun,Dinner,6,india,8.03,53.17
185,20.69,5.00,Male,No,Sun,Dinner,5,india,4.14,25.69
187,30.46,2.00,Male,Yes,Sun,Dinner,5,india,6.09,32.46
216,28.15,3.00,Male,Yes,Sat,Dinner,5,india,5.63,31.15

In [44]:
df.loc[5:10,['tip','size']]

     tip  size
5   4.71     4
6   2.00     2
7   3.12     4
8   1.96     2
9   3.23     2
10  1.71     2

In [48]:
df.loc[100,['day','tip']]

day    Fri
tip    2.5
Name: 100, dtype: object

In [58]:
df[(df['day']=="Sun") & (df['size']>3)].shape[0]
df[(df['day']=="Sun") | (df['time']=="Dinner")].shape[0]

176

In [60]:
df[~(df['day']=="Sun")].shape[0]

168

In [ ]:
df[df['tip']>4]

TypeError: '>' not supported between instances of 'str' and 'int'

In [73]:
df[df['time']=="Dinner"]['day'].value_counts()

day
Sat     87
Sun     76
Fri     12
Thur     1
Name: count, dtype: int64

In [79]:
df['bill_type']='normal'
df.loc[df['total_bill']>40,'bill_type']="Big"
df['bill_type'].value_counts()

bill_type
normal    234
Big        10
Name: count, dtype: int64

In [84]:
t=pd.read_csv('/Users/eshantharjun/Desktop/ml/data/titanicdataset.csv')
t

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [97]:
print(t[t["Age"]>40].shape[0])
print(t[t["Age"]<=40].shape[0])

150
564

In [95]:
t[(t["Age"]>40) & (t["Survived"]==1) & (t['Sex']=="male")].shape[0]
t[(t["Age"]<30) & (t["Survived"]==1) & (t["Sex"]=="female") & (t["Pclass"]==2)].shape[0]

38

In [85]:
t[t['Pclass']==1].shape[0]

216

In [88]:
t[(t['SibSp'] == 0) & (t['Parch'] == 0) & (t['Sex']=="male")].shape[0]

411

In [89]:
(t['Age']<10) & (t['Pclass']==1)

0      False
1      False
2      False
3      False
4      False
       ...
886    False
887    False
888    False
889    False
890    False
Length: 891, dtype: bool