In [2]:
import pandas as pd
import numpy as np

In [3]:
tips=pd.read_csv('/Users/eshantharjun/Desktop/ml/data/tipss.csv')
tips.shape

(244, 7)

In [4]:
tips.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [5]:
tips.groupby('day')['total_bill'].size()

day
Fri     19
Sat     87
Sun     76
Thur    62
Name: total_bill, dtype: int64

In [6]:
tips.groupby('day')['total_bill'].mean()

day
Fri     17.151579
Sat     20.441379
Sun     21.410000
Thur    17.682742
Name: total_bill, dtype: float64

In [7]:
tips.groupby('day')['tip'].mean()

day
Fri     2.734737
Sat     2.993103
Sun     3.255132
Thur    2.771452
Name: tip, dtype: float64

In [8]:
tips.groupby('day').agg(
    Bill_Count=('total_bill','size'),
    Avg_bill=('total_bill','mean'),
    Avg_tip=('tip','mean')
)

      Bill_Count   Avg_bill   Avg_tip
day
Fri           19  17.151579  2.734737
Sat           87  20.441379  2.993103
Sun           76  21.410000  3.255132
Thur          62  17.682742  2.771452

In [9]:
tips.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [10]:
tips.groupby('time').agg(
    bills=('total_bill','size'),
    avg_bill=('total_bill','mean'),
    avg_party=('size','mean')
)

        bills   avg_bill  avg_party
time
Dinner    176  20.797159   2.630682
Lunch      68  17.168676   2.411765

In [11]:
smry = tips.groupby('day').agg(
    bills=('total_bill','size'),
    avg_bill=('total_bill','mean'),
    avg_tip=('tip','mean')
).round(2)
smry

      bills  avg_bill  avg_tip
day
Fri      19     17.15     2.73
Sat      87     20.44     2.99
Sun      76     21.41     3.26
Thur     62     17.68     2.77

In [12]:
print(smry.columns.tolist())
print(smry.index.to_list())
flat=smry.reset_index()
print(flat.columns.tolist())
print(flat[flat["day"]=="Sun"])
flat.head()

['bills', 'avg_bill', 'avg_tip']
['Fri', 'Sat', 'Sun', 'Thur']
['day', 'bills', 'avg_bill', 'avg_tip']
   day  bills  avg_bill  avg_tip
2  Sun     76     21.41     3.26

    day  bills  avg_bill  avg_tip
0   Fri     19     17.15     2.73
1   Sat     87     20.44     2.99
2   Sun     76     21.41     3.26
3  Thur     62     17.68     2.77

In [13]:
smry.to_csv("report.csv")
flat=pd.read_csv('/Users/eshantharjun/Desktop/ml/data/report.csv')
flat.head()

    day  bills  avg_bill  avg_tip
0   Fri     19     17.15     2.73
1   Sat     87     20.44     2.99
2   Sun     76     21.41     3.26
3  Thur     62     17.68     2.77

In [14]:
smoker_report=tips.groupby('smoker').agg(
    bills=('total_bill','size'),
    avg_bill=('total_bill','mean'),
    avg_tip=('tip','mean')
)
smoker_report.reset_index()
smoker_report.to_csv('smoker_report.csv')

smoker=pd.read_csv('smoker_report.csv')
smoker

  smoker  bills   avg_bill   avg_tip
0     No    151  19.188278  2.991854
1    Yes     93  20.756344  3.008710

In [15]:
tips.groupby('day')['tip'].idxmax()

day
Fri      95
Sat     170
Sun     183
Thur    141
Name: tip, dtype: int64

In [16]:
tips.loc[183]

total_bill     23.17
tip              6.5
sex             Male
smoker           Yes
day              Sun
time          Dinner
size               4
Name: 183, dtype: object

In [17]:
tips.groupby('day')['tip'].max()

day
Fri      4.73
Sat     10.00
Sun      6.50
Thur     6.70
Name: tip, dtype: float64

In [18]:
tips["tips_percent"]=tips['tip']/tips['total_bill']

print(tips.groupby('day')['tips_percent'].idxmin())
print(tips.groupby('day')['tips_percent'].idxmax())

day
Fri      90
Sat     237
Sun       0
Thur    146
Name: tips_percent, dtype: int64
day
Fri      93
Sat      67
Sun     172
Thur    149
Name: tips_percent, dtype: int64

In [19]:
bookings = pd.read_csv('/Users/eshantharjun/Desktop/ml/data/bookings.csv')

In [20]:
print(bookings['customer'].str.lower().str.strip())

bookings['customer'] = bookings['customer'].str.lower().str.strip()
print(bookings.head())
bookings['customer'].nunique()

0     ravi sharma
1      priya iyer
2     ravi sharma
3      amit kumar
4     priya  iyer
5     ravi sharma
6       sana khan
7      amit kumar
8      vikram rao
9      sana  khan
10     priya iyer
11     vikram rao
Name: customer, dtype: object
   booking_id     customer  day    time  party_size
0         101  ravi sharma  Sat  Dinner         4.0
1         102   priya iyer  Sat  Dinner         2.0
2         103  ravi sharma  Sun   Lunch         NaN
3         104   amit kumar  Sun  Dinner         6.0
4         105  priya  iyer  Fri  Dinner         NaN

7

In [21]:
tips.groupby('day')['tips_percent'].mean().round(2)

day
Fri     0.17
Sat     0.15
Sun     0.17
Thur    0.16
Name: tips_percent, dtype: float64